CREATE TABLE "Users" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(255) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "phone" varchar(20),
  "full_name" varchar(255) NOT NULL,
  "role" enum(buyer,seller,admin,inspector) NOT NULL DEFAULT 'buyer',
  "avatar_url" varchar(500),
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now()),
  "address" nvarchar(255),
  "CCCD" nvarchar(20)
);

CREATE TABLE "Categories" (
  "category_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "description" text,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "Brands" (
  "brand_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) UNIQUE NOT NULL,
  "country_origin" varchar(100),
  "logo_url" varchar(500)
);

CREATE TABLE "Bicycles" (
  "bicycle_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "seller_id" int NOT NULL,
  "category_id" int NOT NULL,
  "brand_id" int NOT NULL,
  "title" varchar(500) NOT NULL,
  "description" text NOT NULL,
  "price" decimal(15,2) NOT NULL,
  "year_manufacture" int,
  "condition" enum(new,like_new,good,fair) NOT NULL,
  "status" enum(pending,active,sold,hidden,rejected) DEFAULT 'pending',
  "view_count" int DEFAULT 0,
  "is_inspected" boolean DEFAULT false,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "BicycleImages" (
  "image_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "bicycle_id" int NOT NULL,
  "image_url" varchar(500) NOT NULL,
  "is_primary" boolean DEFAULT false,
  "display_order" int DEFAULT 0,
  "created_at" timestamp DEFAULT (now()),
  "manufacture" nvarchar(200)
);

CREATE TABLE "BicycleSpecs" (
  "spec_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "bicycle_id" int UNIQUE NOT NULL,
  "groupset" varchar(255),
  "brake_type" varchar(100),
  "wheel_size" varchar(50),
  "number_of_gears" int,
  "weight_kg" decimal(5,2),
  "frame_size" varchar(50)
);

CREATE TABLE "Wishlists" (
  "wishlist_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "bicycle_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "Messages" (
  "message_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sender_id" int NOT NULL,
  "receiver_id" int NOT NULL,
  "bicycle_id" int,
  "content" text NOT NULL,
  "is_read" boolean DEFAULT false,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "Orders" (
  "order_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_code" varchar(50) UNIQUE NOT NULL,
  "buyer_id" int NOT NULL,
  "total_amount" decimal(15,2) NOT NULL,
  "deposit_amount" decimal(15,2) DEFAULT 0,
  "status" enum(pending,deposited,confirmed,completed,cancelled) DEFAULT 'pending',
  "delivery_date" timestamp,
  "payment_method" enum(cod,bank_transfer,e_wallet) DEFAULT 'cod',
  "shipping_address" nvarchar(500),
  "note" text,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "OrderDetails" (
  "order_detail_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int NOT NULL,
  "bicycle_id" int NOT NULL,
  "seller_id" int NOT NULL,
  "unit_price" decimal(15,2) NOT NULL,
  "quantity" int DEFAULT 1,
  "created_date" timestamp DEFAULT (now())
);

CREATE TABLE "OrderStatusHistory" (
  "history_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int NOT NULL,
  "old_status" varchar(50),
  "new_status" varchar(50) NOT NULL,
  "changed_by" int,
  "note" text,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "Reviews" (
  "review_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int NOT NULL,
  "reviewer_id" int NOT NULL,
  "reviewee_id" int NOT NULL,
  "rating" int NOT NULL,
  "comment" text,
  "review_type" enum(buyer_to_seller,seller_to_buyer) NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "Inspections" (
  "inspection_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "bicycle_id" int NOT NULL,
  "inspector_id" int NOT NULL,
  "status" enum(pending,completed,rejected) DEFAULT 'pending',
  "overall_score" int,
  "summary" text,
  "inspection_fee" decimal(10,2) DEFAULT 0,
  "inspection_date" timestamp,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "Reports" (
  "report_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reporter_id" int NOT NULL,
  "bicycle_id" int,
  "report_type" enum(fraud,fake_info,spam,other) NOT NULL,
  "description" text NOT NULL,
  "status" enum(pending,resolved,rejected) DEFAULT 'pending',
  "created_at" timestamp DEFAULT (now()),
  "resolved_at" timestamp,
  "resolved_by" int
);

CREATE INDEX ON "Users" ("email");

CREATE INDEX ON "Users" ("role");

CREATE INDEX ON "Categories" ("is_active");

CREATE INDEX ON "Brands" ("name");

CREATE INDEX ON "Bicycles" ("seller_id");

CREATE INDEX ON "Bicycles" ("status");

CREATE INDEX ON "Bicycles" ("price");

CREATE INDEX ON "BicycleImages" ("bicycle_id");

CREATE INDEX ON "BicycleSpecs" ("bicycle_id");

CREATE INDEX ON "Wishlists" ("user_id");

CREATE INDEX ON "Wishlists" ("bicycle_id");

CREATE UNIQUE INDEX ON "Wishlists" ("user_id", "bicycle_id");

CREATE INDEX ON "Messages" ("sender_id");

CREATE INDEX ON "Messages" ("receiver_id");

CREATE INDEX ON "Messages" ("bicycle_id");

CREATE INDEX ON "Messages" ("created_at");

CREATE INDEX ON "Orders" ("order_code");

CREATE INDEX ON "Orders" ("buyer_id");

CREATE INDEX ON "Orders" ("status");

CREATE INDEX ON "Orders" ("created_at");

CREATE INDEX ON "OrderDetails" ("order_id");

CREATE INDEX ON "OrderDetails" ("bicycle_id");

CREATE INDEX ON "OrderDetails" ("seller_id");

CREATE INDEX ON "OrderStatusHistory" ("order_id");

CREATE INDEX ON "OrderStatusHistory" ("created_at");

CREATE INDEX ON "Reviews" ("order_id");

CREATE INDEX ON "Reviews" ("reviewer_id");

CREATE INDEX ON "Reviews" ("reviewee_id");

CREATE INDEX ON "Reviews" ("rating");

CREATE INDEX ON "Inspections" ("bicycle_id");

CREATE INDEX ON "Inspections" ("inspector_id");

CREATE INDEX ON "Inspections" ("status");

CREATE INDEX ON "Reports" ("reporter_id");

CREATE INDEX ON "Reports" ("bicycle_id");

CREATE INDEX ON "Reports" ("status");

COMMENT ON COLUMN "OrderDetails"."quantity" IS 'Thường là 1 với xe đã qua sử dụng';

COMMENT ON COLUMN "OrderStatusHistory"."changed_by" IS 'user_id của người thay đổi trạng thái';

COMMENT ON COLUMN "Reviews"."reviewee_id" IS 'Người được đánh giá';

COMMENT ON COLUMN "Reviews"."rating" IS '1-5 stars';

COMMENT ON COLUMN "Inspections"."overall_score" IS '0-100';

COMMENT ON COLUMN "Reports"."resolved_by" IS 'admin user_id';

ALTER TABLE "Bicycles" ADD FOREIGN KEY ("seller_id") REFERENCES "Users" ("user_id");

ALTER TABLE "Bicycles" ADD FOREIGN KEY ("category_id") REFERENCES "Categories" ("category_id");

ALTER TABLE "Bicycles" ADD FOREIGN KEY ("brand_id") REFERENCES "Brands" ("brand_id");

ALTER TABLE "BicycleImages" ADD FOREIGN KEY ("bicycle_id") REFERENCES "Bicycles" ("bicycle_id") ON DELETE CASCADE;

ALTER TABLE "Bicycles" ADD FOREIGN KEY ("bicycle_id") REFERENCES "BicycleSpecs" ("bicycle_id") ON DELETE CASCADE;

ALTER TABLE "Wishlists" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("user_id") ON DELETE CASCADE;

ALTER TABLE "Wishlists" ADD FOREIGN KEY ("bicycle_id") REFERENCES "Bicycles" ("bicycle_id") ON DELETE CASCADE;

ALTER TABLE "Messages" ADD FOREIGN KEY ("sender_id") REFERENCES "Users" ("user_id");

ALTER TABLE "Messages" ADD FOREIGN KEY ("receiver_id") REFERENCES "Users" ("user_id");

ALTER TABLE "Messages" ADD FOREIGN KEY ("bicycle_id") REFERENCES "Bicycles" ("bicycle_id");

ALTER TABLE "Orders" ADD FOREIGN KEY ("buyer_id") REFERENCES "Users" ("user_id");

ALTER TABLE "OrderDetails" ADD FOREIGN KEY ("order_id") REFERENCES "Orders" ("order_id") ON DELETE CASCADE;

ALTER TABLE "OrderDetails" ADD FOREIGN KEY ("bicycle_id") REFERENCES "Bicycles" ("bicycle_id");

ALTER TABLE "OrderDetails" ADD FOREIGN KEY ("seller_id") REFERENCES "Users" ("user_id");

ALTER TABLE "OrderStatusHistory" ADD FOREIGN KEY ("order_id") REFERENCES "Orders" ("order_id") ON DELETE CASCADE;

ALTER TABLE "OrderStatusHistory" ADD FOREIGN KEY ("changed_by") REFERENCES "Users" ("user_id");

ALTER TABLE "Reviews" ADD FOREIGN KEY ("order_id") REFERENCES "Orders" ("order_id");

ALTER TABLE "Reviews" ADD FOREIGN KEY ("reviewer_id") REFERENCES "Users" ("user_id");

ALTER TABLE "Reviews" ADD FOREIGN KEY ("reviewee_id") REFERENCES "Users" ("user_id");

ALTER TABLE "Inspections" ADD FOREIGN KEY ("bicycle_id") REFERENCES "Bicycles" ("bicycle_id");

ALTER TABLE "Inspections" ADD FOREIGN KEY ("inspector_id") REFERENCES "Users" ("user_id");

ALTER TABLE "Reports" ADD FOREIGN KEY ("reporter_id") REFERENCES "Users" ("user_id");

ALTER TABLE "Reports" ADD FOREIGN KEY ("bicycle_id") REFERENCES "Bicycles" ("bicycle_id");

ALTER TABLE "Reports" ADD FOREIGN KEY ("resolved_by") REFERENCES "Users" ("user_id");
